### PR TITLE
Fix HTTP Error 414 Request URI too long

### PR DESCRIPTION
**Pull request by a2exfr**
Fix HTTP Error 414 Request URI too long

### CODE REVIEW

**Comment by a2exfr** [comment]
When using ck-editor field with a little bit longer info, I get this error.

This is 100% working fix.

**Comment by juek** [comment]
I already thought we might run into this with larger content.
Have you considered to use [$gp.postC()](https://github.com/Typesetter/Typesetter/blob/5966a684550a4565517ef27865c58b398b4ae42c/include/js/main.js#L108)?

(edit:  I used this in SectionClipboard.js, line 126+ )

**Comment by a2exfr** [comment]
Lol. Have no idea it exists. I definitely have to look more in TS js files.   it's minified  and ...
May be merge this and I try to rewrite with gp.postC later?

**Comment by juek** [comment]
I will merge but have conflicts with my current local base. 
So please be patient- it may take 1 hour or 2 (says me LOL... it will take at least 3).

**Comment by juek** [comment]
> it's minified and ...

Always good to look up stuff on GitHub. Would have saved me some 100 hours if I would have started earlier doing so.

**Comment by juek** [comment]
I changed updateSection to always post using $gp.postC(), see [commit](https://github.com/juek/CustomSections/commit/c01c1b73b563d5c6611aa4107edc51ef028a7710)

**Pull request closed without merging**
